version: '3.8'

services:
  db:
    image: postgres:12.2
    env_file:
      - docker-compose.env
    ports:
      - "5432:5432"

    volumes: 
      - db-data:/var/lib/postgresql/data
    networks:
      - medimooc_network


  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - docker-compose.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - medimooc_network
  
volumes: 
  db-data:
  pgadmin-data:

networks:
  medimooc_network:
    driver: bridge

